version: '3'

services:
  app:
    container_name: lara-vue-app
    build: ./
    volumes:
      - ./src/LaravelVue:/home/LaravelVue
    depends_on:
      - mariadb
      
  nginx:
    container_name: lara-vue-nginx
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./src/LaravelVue:/home/LaravelVue
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    container_name: lara-vue-php
    image: php:7.4-fpm
    volumes:
      - ./src/LaravelVue:/home/LaravelVue
      - ./phpini/php-ini/php.ini:/usr/local/etc/php/conf.d/php.ini

  mariadb:
    container_name: lara-vue-mariadb
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd6421

  phpmyadmin:
    container_name: lara-vue-phpmyadmin
    image: phpmyadmin/phpmyadmin
    links: 
      - mariadb:db
    ports:
      - 8765:80
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd6421
      UPLOAD_LIMIT: 300000000
    depends_on:
      - mariadb
      
  redis:
    container_name: lara-vue-redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    restart: always
    
 
